name: EduMania
main: info.plugmania.EduMania.EduMania
version: 1.0
description: >
             A free server package for the educational use of minecraft.
commands:
    auth:
      description: Used to authenticate all connecting clients.
      usage: /auth key
    txdl:
      description: Used by client to download custom texture pack.
      usage: /txdl URL|localfilename
    txrl:
      description: Used by client to reload their texture pack.
      usage: /txrl
      